// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/temporalio/cloud-cli/internal/cert"
	"github.com/temporalio/cloud-cli/internal/namespace"
	"github.com/temporalio/cloud-cli/temporalcloudcli"
	namespace0 "go.temporal.io/cloud-sdk/api/namespace/v1"
	"go.temporal.io/cloud-sdk/api/operation/v1"
	"google.golang.org/protobuf/proto"
)

// NewMockNamespaceClient creates a new instance of MockNamespaceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamespaceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamespaceClient {
	mock := &MockNamespaceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNamespaceClient is an autogenerated mock type for the NamespaceClient type
type MockNamespaceClient struct {
	mock.Mock
}

type MockNamespaceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamespaceClient) EXPECT() *MockNamespaceClient_Expecter {
	return &MockNamespaceClient_Expecter{mock: &_m.Mock}
}

// AddCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) AddCACerts(context1 context.Context, addCACertsParams namespace.AddCACertsParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, addCACertsParams)

	if len(ret) == 0 {
		panic("no return value specified for AddCACerts")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCACertsParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, addCACertsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCACertsParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, addCACertsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.AddCACertsParams) error); ok {
		r1 = returnFunc(context1, addCACertsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_AddCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCACerts'
type MockNamespaceClient_AddCACerts_Call struct {
	*mock.Call
}

// AddCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - addCACertsParams namespace.AddCACertsParams
func (_e *MockNamespaceClient_Expecter) AddCACerts(context1 interface{}, addCACertsParams interface{}) *MockNamespaceClient_AddCACerts_Call {
	return &MockNamespaceClient_AddCACerts_Call{Call: _e.mock.On("AddCACerts", context1, addCACertsParams)}
}

func (_c *MockNamespaceClient_AddCACerts_Call) Run(run func(context1 context.Context, addCACertsParams namespace.AddCACertsParams)) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.AddCACertsParams
		if args[1] != nil {
			arg1 = args[1].(namespace.AddCACertsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_AddCACerts_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_AddCACerts_Call) RunAndReturn(run func(context1 context.Context, addCACertsParams namespace.AddCACertsParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// AddCertFilters provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) AddCertFilters(context1 context.Context, addCertFiltersParams namespace.AddCertFiltersParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, addCertFiltersParams)

	if len(ret) == 0 {
		panic("no return value specified for AddCertFilters")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCertFiltersParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, addCertFiltersParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCertFiltersParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, addCertFiltersParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.AddCertFiltersParams) error); ok {
		r1 = returnFunc(context1, addCertFiltersParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_AddCertFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCertFilters'
type MockNamespaceClient_AddCertFilters_Call struct {
	*mock.Call
}

// AddCertFilters is a helper method to define mock.On call
//   - context1 context.Context
//   - addCertFiltersParams namespace.AddCertFiltersParams
func (_e *MockNamespaceClient_Expecter) AddCertFilters(context1 interface{}, addCertFiltersParams interface{}) *MockNamespaceClient_AddCertFilters_Call {
	return &MockNamespaceClient_AddCertFilters_Call{Call: _e.mock.On("AddCertFilters", context1, addCertFiltersParams)}
}

func (_c *MockNamespaceClient_AddCertFilters_Call) Run(run func(context1 context.Context, addCertFiltersParams namespace.AddCertFiltersParams)) *MockNamespaceClient_AddCertFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.AddCertFiltersParams
		if args[1] != nil {
			arg1 = args[1].(namespace.AddCertFiltersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_AddCertFilters_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_AddCertFilters_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_AddCertFilters_Call) RunAndReturn(run func(context1 context.Context, addCertFiltersParams namespace.AddCertFiltersParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_AddCertFilters_Call {
	_c.Call.Return(run)
	return _c
}

// AddRegion provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) AddRegion(context1 context.Context, addRegionParams namespace.AddRegionParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, addRegionParams)

	if len(ret) == 0 {
		panic("no return value specified for AddRegion")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddRegionParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, addRegionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddRegionParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, addRegionParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.AddRegionParams) error); ok {
		r1 = returnFunc(context1, addRegionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_AddRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRegion'
type MockNamespaceClient_AddRegion_Call struct {
	*mock.Call
}

// AddRegion is a helper method to define mock.On call
//   - context1 context.Context
//   - addRegionParams namespace.AddRegionParams
func (_e *MockNamespaceClient_Expecter) AddRegion(context1 interface{}, addRegionParams interface{}) *MockNamespaceClient_AddRegion_Call {
	return &MockNamespaceClient_AddRegion_Call{Call: _e.mock.On("AddRegion", context1, addRegionParams)}
}

func (_c *MockNamespaceClient_AddRegion_Call) Run(run func(context1 context.Context, addRegionParams namespace.AddRegionParams)) *MockNamespaceClient_AddRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.AddRegionParams
		if args[1] != nil {
			arg1 = args[1].(namespace.AddRegionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_AddRegion_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_AddRegion_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_AddRegion_Call) RunAndReturn(run func(context1 context.Context, addRegionParams namespace.AddRegionParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_AddRegion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) CreateExportSink(context1 context.Context, createExportSinkParams namespace.CreateExportSinkParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, createExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateExportSink")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.CreateExportSinkParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, createExportSinkParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.CreateExportSinkParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, createExportSinkParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.CreateExportSinkParams) error); ok {
		r1 = returnFunc(context1, createExportSinkParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_CreateExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExportSink'
type MockNamespaceClient_CreateExportSink_Call struct {
	*mock.Call
}

// CreateExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - createExportSinkParams namespace.CreateExportSinkParams
func (_e *MockNamespaceClient_Expecter) CreateExportSink(context1 interface{}, createExportSinkParams interface{}) *MockNamespaceClient_CreateExportSink_Call {
	return &MockNamespaceClient_CreateExportSink_Call{Call: _e.mock.On("CreateExportSink", context1, createExportSinkParams)}
}

func (_c *MockNamespaceClient_CreateExportSink_Call) Run(run func(context1 context.Context, createExportSinkParams namespace.CreateExportSinkParams)) *MockNamespaceClient_CreateExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.CreateExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.CreateExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_CreateExportSink_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_CreateExportSink_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_CreateExportSink_Call) RunAndReturn(run func(context1 context.Context, createExportSinkParams namespace.CreateExportSinkParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_CreateExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSearchAttribute provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) CreateSearchAttribute(context1 context.Context, createSearchAttributeParams namespace.CreateSearchAttributeParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, createSearchAttributeParams)

	if len(ret) == 0 {
		panic("no return value specified for CreateSearchAttribute")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.CreateSearchAttributeParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, createSearchAttributeParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.CreateSearchAttributeParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, createSearchAttributeParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.CreateSearchAttributeParams) error); ok {
		r1 = returnFunc(context1, createSearchAttributeParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_CreateSearchAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSearchAttribute'
type MockNamespaceClient_CreateSearchAttribute_Call struct {
	*mock.Call
}

// CreateSearchAttribute is a helper method to define mock.On call
//   - context1 context.Context
//   - createSearchAttributeParams namespace.CreateSearchAttributeParams
func (_e *MockNamespaceClient_Expecter) CreateSearchAttribute(context1 interface{}, createSearchAttributeParams interface{}) *MockNamespaceClient_CreateSearchAttribute_Call {
	return &MockNamespaceClient_CreateSearchAttribute_Call{Call: _e.mock.On("CreateSearchAttribute", context1, createSearchAttributeParams)}
}

func (_c *MockNamespaceClient_CreateSearchAttribute_Call) Run(run func(context1 context.Context, createSearchAttributeParams namespace.CreateSearchAttributeParams)) *MockNamespaceClient_CreateSearchAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.CreateSearchAttributeParams
		if args[1] != nil {
			arg1 = args[1].(namespace.CreateSearchAttributeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_CreateSearchAttribute_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_CreateSearchAttribute_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_CreateSearchAttribute_Call) RunAndReturn(run func(context1 context.Context, createSearchAttributeParams namespace.CreateSearchAttributeParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_CreateSearchAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteCACerts(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteCACertsParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCACerts")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCACertsParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteCACertsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCACertsParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteCACertsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteCACertsParams) error); ok {
		r1 = returnFunc(context1, deleteCACertsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCACerts'
type MockNamespaceClient_DeleteCACerts_Call struct {
	*mock.Call
}

// DeleteCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteCACertsParams namespace.DeleteCACertsParams
func (_e *MockNamespaceClient_Expecter) DeleteCACerts(context1 interface{}, deleteCACertsParams interface{}) *MockNamespaceClient_DeleteCACerts_Call {
	return &MockNamespaceClient_DeleteCACerts_Call{Call: _e.mock.On("DeleteCACerts", context1, deleteCACertsParams)}
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) Run(run func(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams)) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteCACertsParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteCACertsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) RunAndReturn(run func(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertFilters provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteCertFilters(context1 context.Context, deleteCertFiltersParams namespace.DeleteCertFiltersParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteCertFiltersParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertFilters")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCertFiltersParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteCertFiltersParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCertFiltersParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteCertFiltersParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteCertFiltersParams) error); ok {
		r1 = returnFunc(context1, deleteCertFiltersParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteCertFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertFilters'
type MockNamespaceClient_DeleteCertFilters_Call struct {
	*mock.Call
}

// DeleteCertFilters is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteCertFiltersParams namespace.DeleteCertFiltersParams
func (_e *MockNamespaceClient_Expecter) DeleteCertFilters(context1 interface{}, deleteCertFiltersParams interface{}) *MockNamespaceClient_DeleteCertFilters_Call {
	return &MockNamespaceClient_DeleteCertFilters_Call{Call: _e.mock.On("DeleteCertFilters", context1, deleteCertFiltersParams)}
}

func (_c *MockNamespaceClient_DeleteCertFilters_Call) Run(run func(context1 context.Context, deleteCertFiltersParams namespace.DeleteCertFiltersParams)) *MockNamespaceClient_DeleteCertFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteCertFiltersParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteCertFiltersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteCertFilters_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteCertFilters_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteCertFilters_Call) RunAndReturn(run func(context1 context.Context, deleteCertFiltersParams namespace.DeleteCertFiltersParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteCertFilters_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCodec provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteCodec(context1 context.Context, deleteCodecParams namespace.DeleteCodecParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteCodecParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCodec")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCodecParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteCodecParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCodecParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteCodecParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteCodecParams) error); ok {
		r1 = returnFunc(context1, deleteCodecParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteCodec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCodec'
type MockNamespaceClient_DeleteCodec_Call struct {
	*mock.Call
}

// DeleteCodec is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteCodecParams namespace.DeleteCodecParams
func (_e *MockNamespaceClient_Expecter) DeleteCodec(context1 interface{}, deleteCodecParams interface{}) *MockNamespaceClient_DeleteCodec_Call {
	return &MockNamespaceClient_DeleteCodec_Call{Call: _e.mock.On("DeleteCodec", context1, deleteCodecParams)}
}

func (_c *MockNamespaceClient_DeleteCodec_Call) Run(run func(context1 context.Context, deleteCodecParams namespace.DeleteCodecParams)) *MockNamespaceClient_DeleteCodec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteCodecParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteCodecParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteCodec_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteCodec_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteCodec_Call) RunAndReturn(run func(context1 context.Context, deleteCodecParams namespace.DeleteCodecParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteCodec_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteExportSink(context1 context.Context, deleteExportSinkParams namespace.DeleteExportSinkParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExportSink")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteExportSinkParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteExportSinkParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteExportSinkParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteExportSinkParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteExportSinkParams) error); ok {
		r1 = returnFunc(context1, deleteExportSinkParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExportSink'
type MockNamespaceClient_DeleteExportSink_Call struct {
	*mock.Call
}

// DeleteExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteExportSinkParams namespace.DeleteExportSinkParams
func (_e *MockNamespaceClient_Expecter) DeleteExportSink(context1 interface{}, deleteExportSinkParams interface{}) *MockNamespaceClient_DeleteExportSink_Call {
	return &MockNamespaceClient_DeleteExportSink_Call{Call: _e.mock.On("DeleteExportSink", context1, deleteExportSinkParams)}
}

func (_c *MockNamespaceClient_DeleteExportSink_Call) Run(run func(context1 context.Context, deleteExportSinkParams namespace.DeleteExportSinkParams)) *MockNamespaceClient_DeleteExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteExportSink_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteExportSink_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteExportSink_Call) RunAndReturn(run func(context1 context.Context, deleteExportSinkParams namespace.DeleteExportSinkParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTags provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteTags(context1 context.Context, deleteTagsParams namespace.DeleteTagsParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteTagsParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTags")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteTagsParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteTagsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteTagsParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteTagsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteTagsParams) error); ok {
		r1 = returnFunc(context1, deleteTagsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTags'
type MockNamespaceClient_DeleteTags_Call struct {
	*mock.Call
}

// DeleteTags is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteTagsParams namespace.DeleteTagsParams
func (_e *MockNamespaceClient_Expecter) DeleteTags(context1 interface{}, deleteTagsParams interface{}) *MockNamespaceClient_DeleteTags_Call {
	return &MockNamespaceClient_DeleteTags_Call{Call: _e.mock.On("DeleteTags", context1, deleteTagsParams)}
}

func (_c *MockNamespaceClient_DeleteTags_Call) Run(run func(context1 context.Context, deleteTagsParams namespace.DeleteTagsParams)) *MockNamespaceClient_DeleteTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteTagsParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteTagsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteTags_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteTags_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteTags_Call) RunAndReturn(run func(context1 context.Context, deleteTagsParams namespace.DeleteTagsParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteTags_Call {
	_c.Call.Return(run)
	return _c
}

// DisableExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DisableExportSink(context1 context.Context, disableExportSinkParams namespace.DisableExportSinkParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, disableExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for DisableExportSink")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DisableExportSinkParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, disableExportSinkParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DisableExportSinkParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, disableExportSinkParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DisableExportSinkParams) error); ok {
		r1 = returnFunc(context1, disableExportSinkParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DisableExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableExportSink'
type MockNamespaceClient_DisableExportSink_Call struct {
	*mock.Call
}

// DisableExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - disableExportSinkParams namespace.DisableExportSinkParams
func (_e *MockNamespaceClient_Expecter) DisableExportSink(context1 interface{}, disableExportSinkParams interface{}) *MockNamespaceClient_DisableExportSink_Call {
	return &MockNamespaceClient_DisableExportSink_Call{Call: _e.mock.On("DisableExportSink", context1, disableExportSinkParams)}
}

func (_c *MockNamespaceClient_DisableExportSink_Call) Run(run func(context1 context.Context, disableExportSinkParams namespace.DisableExportSinkParams)) *MockNamespaceClient_DisableExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DisableExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DisableExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DisableExportSink_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DisableExportSink_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DisableExportSink_Call) RunAndReturn(run func(context1 context.Context, disableExportSinkParams namespace.DisableExportSinkParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DisableExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// EnableExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) EnableExportSink(context1 context.Context, enableExportSinkParams namespace.EnableExportSinkParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, enableExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for EnableExportSink")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.EnableExportSinkParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, enableExportSinkParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.EnableExportSinkParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, enableExportSinkParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.EnableExportSinkParams) error); ok {
		r1 = returnFunc(context1, enableExportSinkParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_EnableExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableExportSink'
type MockNamespaceClient_EnableExportSink_Call struct {
	*mock.Call
}

// EnableExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - enableExportSinkParams namespace.EnableExportSinkParams
func (_e *MockNamespaceClient_Expecter) EnableExportSink(context1 interface{}, enableExportSinkParams interface{}) *MockNamespaceClient_EnableExportSink_Call {
	return &MockNamespaceClient_EnableExportSink_Call{Call: _e.mock.On("EnableExportSink", context1, enableExportSinkParams)}
}

func (_c *MockNamespaceClient_EnableExportSink_Call) Run(run func(context1 context.Context, enableExportSinkParams namespace.EnableExportSinkParams)) *MockNamespaceClient_EnableExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.EnableExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.EnableExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_EnableExportSink_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_EnableExportSink_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_EnableExportSink_Call) RunAndReturn(run func(context1 context.Context, enableExportSinkParams namespace.EnableExportSinkParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_EnableExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// Failover provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) Failover(context1 context.Context, failoverParams namespace.FailoverParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, failoverParams)

	if len(ret) == 0 {
		panic("no return value specified for Failover")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.FailoverParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, failoverParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.FailoverParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, failoverParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.FailoverParams) error); ok {
		r1 = returnFunc(context1, failoverParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_Failover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Failover'
type MockNamespaceClient_Failover_Call struct {
	*mock.Call
}

// Failover is a helper method to define mock.On call
//   - context1 context.Context
//   - failoverParams namespace.FailoverParams
func (_e *MockNamespaceClient_Expecter) Failover(context1 interface{}, failoverParams interface{}) *MockNamespaceClient_Failover_Call {
	return &MockNamespaceClient_Failover_Call{Call: _e.mock.On("Failover", context1, failoverParams)}
}

func (_c *MockNamespaceClient_Failover_Call) Run(run func(context1 context.Context, failoverParams namespace.FailoverParams)) *MockNamespaceClient_Failover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.FailoverParams
		if args[1] != nil {
			arg1 = args[1].(namespace.FailoverParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_Failover_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_Failover_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_Failover_Call) RunAndReturn(run func(context1 context.Context, failoverParams namespace.FailoverParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_Failover_Call {
	_c.Call.Return(run)
	return _c
}

// GetCodecServer provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) GetCodecServer(context1 context.Context, s string) (*namespace0.CodecServerSpec, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetCodecServer")
	}

	var r0 *namespace0.CodecServerSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*namespace0.CodecServerSpec, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *namespace0.CodecServerSpec); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*namespace0.CodecServerSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_GetCodecServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCodecServer'
type MockNamespaceClient_GetCodecServer_Call struct {
	*mock.Call
}

// GetCodecServer is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) GetCodecServer(context1 interface{}, s interface{}) *MockNamespaceClient_GetCodecServer_Call {
	return &MockNamespaceClient_GetCodecServer_Call{Call: _e.mock.On("GetCodecServer", context1, s)}
}

func (_c *MockNamespaceClient_GetCodecServer_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_GetCodecServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_GetCodecServer_Call) Return(codecServerSpec *namespace0.CodecServerSpec, err error) *MockNamespaceClient_GetCodecServer_Call {
	_c.Call.Return(codecServerSpec, err)
	return _c
}

func (_c *MockNamespaceClient_GetCodecServer_Call) RunAndReturn(run func(context1 context.Context, s string) (*namespace0.CodecServerSpec, error)) *MockNamespaceClient_GetCodecServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) GetExportSink(context1 context.Context, s string, s1 string) (*namespace0.ExportSink, error) {
	ret := _mock.Called(context1, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetExportSink")
	}

	var r0 *namespace0.ExportSink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*namespace0.ExportSink, error)); ok {
		return returnFunc(context1, s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *namespace0.ExportSink); ok {
		r0 = returnFunc(context1, s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*namespace0.ExportSink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(context1, s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_GetExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExportSink'
type MockNamespaceClient_GetExportSink_Call struct {
	*mock.Call
}

// GetExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
func (_e *MockNamespaceClient_Expecter) GetExportSink(context1 interface{}, s interface{}, s1 interface{}) *MockNamespaceClient_GetExportSink_Call {
	return &MockNamespaceClient_GetExportSink_Call{Call: _e.mock.On("GetExportSink", context1, s, s1)}
}

func (_c *MockNamespaceClient_GetExportSink_Call) Run(run func(context1 context.Context, s string, s1 string)) *MockNamespaceClient_GetExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_GetExportSink_Call) Return(exportSink *namespace0.ExportSink, err error) *MockNamespaceClient_GetExportSink_Call {
	_c.Call.Return(exportSink, err)
	return _c
}

func (_c *MockNamespaceClient_GetExportSink_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string) (*namespace0.ExportSink, error)) *MockNamespaceClient_GetExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) GetNamespace(context1 context.Context, s string) (*namespace0.Namespace, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *namespace0.Namespace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*namespace0.Namespace, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *namespace0.Namespace); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*namespace0.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockNamespaceClient_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) GetNamespace(context1 interface{}, s interface{}) *MockNamespaceClient_GetNamespace_Call {
	return &MockNamespaceClient_GetNamespace_Call{Call: _e.mock.On("GetNamespace", context1, s)}
}

func (_c *MockNamespaceClient_GetNamespace_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_GetNamespace_Call) Return(namespace1 *namespace0.Namespace, err error) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Return(namespace1, err)
	return _c
}

func (_c *MockNamespaceClient_GetNamespace_Call) RunAndReturn(run func(context1 context.Context, s string) (*namespace0.Namespace, error)) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// ListCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListCACerts(context1 context.Context, s string) ([]cert.CACert, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListCACerts")
	}

	var r0 []cert.CACert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]cert.CACert, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []cert.CACert); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cert.CACert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCACerts'
type MockNamespaceClient_ListCACerts_Call struct {
	*mock.Call
}

// ListCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListCACerts(context1 interface{}, s interface{}) *MockNamespaceClient_ListCACerts_Call {
	return &MockNamespaceClient_ListCACerts_Call{Call: _e.mock.On("ListCACerts", context1, s)}
}

func (_c *MockNamespaceClient_ListCACerts_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListCACerts_Call) Return(cACerts []cert.CACert, err error) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Return(cACerts, err)
	return _c
}

func (_c *MockNamespaceClient_ListCACerts_Call) RunAndReturn(run func(context1 context.Context, s string) ([]cert.CACert, error)) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertFilters provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListCertFilters(context1 context.Context, s string) ([]*namespace0.CertificateFilterSpec, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListCertFilters")
	}

	var r0 []*namespace0.CertificateFilterSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*namespace0.CertificateFilterSpec, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*namespace0.CertificateFilterSpec); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*namespace0.CertificateFilterSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListCertFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertFilters'
type MockNamespaceClient_ListCertFilters_Call struct {
	*mock.Call
}

// ListCertFilters is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListCertFilters(context1 interface{}, s interface{}) *MockNamespaceClient_ListCertFilters_Call {
	return &MockNamespaceClient_ListCertFilters_Call{Call: _e.mock.On("ListCertFilters", context1, s)}
}

func (_c *MockNamespaceClient_ListCertFilters_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListCertFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListCertFilters_Call) Return(certificateFilterSpecs []*namespace0.CertificateFilterSpec, err error) *MockNamespaceClient_ListCertFilters_Call {
	_c.Call.Return(certificateFilterSpecs, err)
	return _c
}

func (_c *MockNamespaceClient_ListCertFilters_Call) RunAndReturn(run func(context1 context.Context, s string) ([]*namespace0.CertificateFilterSpec, error)) *MockNamespaceClient_ListCertFilters_Call {
	_c.Call.Return(run)
	return _c
}

// ListExportSinks provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListExportSinks(context1 context.Context, s string) ([]*namespace0.ExportSink, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListExportSinks")
	}

	var r0 []*namespace0.ExportSink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*namespace0.ExportSink, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*namespace0.ExportSink); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*namespace0.ExportSink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListExportSinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExportSinks'
type MockNamespaceClient_ListExportSinks_Call struct {
	*mock.Call
}

// ListExportSinks is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListExportSinks(context1 interface{}, s interface{}) *MockNamespaceClient_ListExportSinks_Call {
	return &MockNamespaceClient_ListExportSinks_Call{Call: _e.mock.On("ListExportSinks", context1, s)}
}

func (_c *MockNamespaceClient_ListExportSinks_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListExportSinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListExportSinks_Call) Return(exportSinks []*namespace0.ExportSink, err error) *MockNamespaceClient_ListExportSinks_Call {
	_c.Call.Return(exportSinks, err)
	return _c
}

func (_c *MockNamespaceClient_ListExportSinks_Call) RunAndReturn(run func(context1 context.Context, s string) ([]*namespace0.ExportSink, error)) *MockNamespaceClient_ListExportSinks_Call {
	_c.Call.Return(run)
	return _c
}

// ListRegions provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListRegions(context1 context.Context, s string) ([]namespace.RegionStatus, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListRegions")
	}

	var r0 []namespace.RegionStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]namespace.RegionStatus, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []namespace.RegionStatus); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]namespace.RegionStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListRegions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRegions'
type MockNamespaceClient_ListRegions_Call struct {
	*mock.Call
}

// ListRegions is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListRegions(context1 interface{}, s interface{}) *MockNamespaceClient_ListRegions_Call {
	return &MockNamespaceClient_ListRegions_Call{Call: _e.mock.On("ListRegions", context1, s)}
}

func (_c *MockNamespaceClient_ListRegions_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListRegions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListRegions_Call) Return(regionStatuss []namespace.RegionStatus, err error) *MockNamespaceClient_ListRegions_Call {
	_c.Call.Return(regionStatuss, err)
	return _c
}

func (_c *MockNamespaceClient_ListRegions_Call) RunAndReturn(run func(context1 context.Context, s string) ([]namespace.RegionStatus, error)) *MockNamespaceClient_ListRegions_Call {
	_c.Call.Return(run)
	return _c
}

// ListSearchAttributes provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListSearchAttributes(context1 context.Context, s string) ([]namespace.SearchAttribute, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListSearchAttributes")
	}

	var r0 []namespace.SearchAttribute
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]namespace.SearchAttribute, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []namespace.SearchAttribute); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]namespace.SearchAttribute)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListSearchAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSearchAttributes'
type MockNamespaceClient_ListSearchAttributes_Call struct {
	*mock.Call
}

// ListSearchAttributes is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListSearchAttributes(context1 interface{}, s interface{}) *MockNamespaceClient_ListSearchAttributes_Call {
	return &MockNamespaceClient_ListSearchAttributes_Call{Call: _e.mock.On("ListSearchAttributes", context1, s)}
}

func (_c *MockNamespaceClient_ListSearchAttributes_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListSearchAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListSearchAttributes_Call) Return(searchAttributes []namespace.SearchAttribute, err error) *MockNamespaceClient_ListSearchAttributes_Call {
	_c.Call.Return(searchAttributes, err)
	return _c
}

func (_c *MockNamespaceClient_ListSearchAttributes_Call) RunAndReturn(run func(context1 context.Context, s string) ([]namespace.SearchAttribute, error)) *MockNamespaceClient_ListSearchAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListTags(context1 context.Context, s string) ([]namespace.Tag, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []namespace.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]namespace.Tag, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []namespace.Tag); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]namespace.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type MockNamespaceClient_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListTags(context1 interface{}, s interface{}) *MockNamespaceClient_ListTags_Call {
	return &MockNamespaceClient_ListTags_Call{Call: _e.mock.On("ListTags", context1, s)}
}

func (_c *MockNamespaceClient_ListTags_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListTags_Call) Return(tags []namespace.Tag, err error) *MockNamespaceClient_ListTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockNamespaceClient_ListTags_Call) RunAndReturn(run func(context1 context.Context, s string) ([]namespace.Tag, error)) *MockNamespaceClient_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveRegion provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) RemoveRegion(context1 context.Context, removeRegionParams namespace.RemoveRegionParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, removeRegionParams)

	if len(ret) == 0 {
		panic("no return value specified for RemoveRegion")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.RemoveRegionParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, removeRegionParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.RemoveRegionParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, removeRegionParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.RemoveRegionParams) error); ok {
		r1 = returnFunc(context1, removeRegionParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_RemoveRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveRegion'
type MockNamespaceClient_RemoveRegion_Call struct {
	*mock.Call
}

// RemoveRegion is a helper method to define mock.On call
//   - context1 context.Context
//   - removeRegionParams namespace.RemoveRegionParams
func (_e *MockNamespaceClient_Expecter) RemoveRegion(context1 interface{}, removeRegionParams interface{}) *MockNamespaceClient_RemoveRegion_Call {
	return &MockNamespaceClient_RemoveRegion_Call{Call: _e.mock.On("RemoveRegion", context1, removeRegionParams)}
}

func (_c *MockNamespaceClient_RemoveRegion_Call) Run(run func(context1 context.Context, removeRegionParams namespace.RemoveRegionParams)) *MockNamespaceClient_RemoveRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.RemoveRegionParams
		if args[1] != nil {
			arg1 = args[1].(namespace.RemoveRegionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_RemoveRegion_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_RemoveRegion_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_RemoveRegion_Call) RunAndReturn(run func(context1 context.Context, removeRegionParams namespace.RemoveRegionParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_RemoveRegion_Call {
	_c.Call.Return(run)
	return _c
}

// RenameSearchAttribute provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) RenameSearchAttribute(context1 context.Context, renameSearchAttributeParams namespace.RenameSearchAttributeParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, renameSearchAttributeParams)

	if len(ret) == 0 {
		panic("no return value specified for RenameSearchAttribute")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.RenameSearchAttributeParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, renameSearchAttributeParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.RenameSearchAttributeParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, renameSearchAttributeParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.RenameSearchAttributeParams) error); ok {
		r1 = returnFunc(context1, renameSearchAttributeParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_RenameSearchAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameSearchAttribute'
type MockNamespaceClient_RenameSearchAttribute_Call struct {
	*mock.Call
}

// RenameSearchAttribute is a helper method to define mock.On call
//   - context1 context.Context
//   - renameSearchAttributeParams namespace.RenameSearchAttributeParams
func (_e *MockNamespaceClient_Expecter) RenameSearchAttribute(context1 interface{}, renameSearchAttributeParams interface{}) *MockNamespaceClient_RenameSearchAttribute_Call {
	return &MockNamespaceClient_RenameSearchAttribute_Call{Call: _e.mock.On("RenameSearchAttribute", context1, renameSearchAttributeParams)}
}

func (_c *MockNamespaceClient_RenameSearchAttribute_Call) Run(run func(context1 context.Context, renameSearchAttributeParams namespace.RenameSearchAttributeParams)) *MockNamespaceClient_RenameSearchAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.RenameSearchAttributeParams
		if args[1] != nil {
			arg1 = args[1].(namespace.RenameSearchAttributeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_RenameSearchAttribute_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_RenameSearchAttribute_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_RenameSearchAttribute_Call) RunAndReturn(run func(context1 context.Context, renameSearchAttributeParams namespace.RenameSearchAttributeParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_RenameSearchAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// SetCodec provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) SetCodec(context1 context.Context, setCodecParams namespace.SetCodecParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, setCodecParams)

	if len(ret) == 0 {
		panic("no return value specified for SetCodec")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.SetCodecParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, setCodecParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.SetCodecParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, setCodecParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.SetCodecParams) error); ok {
		r1 = returnFunc(context1, setCodecParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_SetCodec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCodec'
type MockNamespaceClient_SetCodec_Call struct {
	*mock.Call
}

// SetCodec is a helper method to define mock.On call
//   - context1 context.Context
//   - setCodecParams namespace.SetCodecParams
func (_e *MockNamespaceClient_Expecter) SetCodec(context1 interface{}, setCodecParams interface{}) *MockNamespaceClient_SetCodec_Call {
	return &MockNamespaceClient_SetCodec_Call{Call: _e.mock.On("SetCodec", context1, setCodecParams)}
}

func (_c *MockNamespaceClient_SetCodec_Call) Run(run func(context1 context.Context, setCodecParams namespace.SetCodecParams)) *MockNamespaceClient_SetCodec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.SetCodecParams
		if args[1] != nil {
			arg1 = args[1].(namespace.SetCodecParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_SetCodec_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_SetCodec_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_SetCodec_Call) RunAndReturn(run func(context1 context.Context, setCodecParams namespace.SetCodecParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_SetCodec_Call {
	_c.Call.Return(run)
	return _c
}

// SetTag provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) SetTag(context1 context.Context, setTagParams namespace.SetTagParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, setTagParams)

	if len(ret) == 0 {
		panic("no return value specified for SetTag")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.SetTagParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, setTagParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.SetTagParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, setTagParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.SetTagParams) error); ok {
		r1 = returnFunc(context1, setTagParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_SetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTag'
type MockNamespaceClient_SetTag_Call struct {
	*mock.Call
}

// SetTag is a helper method to define mock.On call
//   - context1 context.Context
//   - setTagParams namespace.SetTagParams
func (_e *MockNamespaceClient_Expecter) SetTag(context1 interface{}, setTagParams interface{}) *MockNamespaceClient_SetTag_Call {
	return &MockNamespaceClient_SetTag_Call{Call: _e.mock.On("SetTag", context1, setTagParams)}
}

func (_c *MockNamespaceClient_SetTag_Call) Run(run func(context1 context.Context, setTagParams namespace.SetTagParams)) *MockNamespaceClient_SetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.SetTagParams
		if args[1] != nil {
			arg1 = args[1].(namespace.SetTagParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_SetTag_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_SetTag_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_SetTag_Call) RunAndReturn(run func(context1 context.Context, setTagParams namespace.SetTagParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_SetTag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) UpdateExportSink(context1 context.Context, updateExportSinkParams namespace.UpdateExportSinkParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, updateExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExportSink")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateExportSinkParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, updateExportSinkParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateExportSinkParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, updateExportSinkParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.UpdateExportSinkParams) error); ok {
		r1 = returnFunc(context1, updateExportSinkParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_UpdateExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExportSink'
type MockNamespaceClient_UpdateExportSink_Call struct {
	*mock.Call
}

// UpdateExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - updateExportSinkParams namespace.UpdateExportSinkParams
func (_e *MockNamespaceClient_Expecter) UpdateExportSink(context1 interface{}, updateExportSinkParams interface{}) *MockNamespaceClient_UpdateExportSink_Call {
	return &MockNamespaceClient_UpdateExportSink_Call{Call: _e.mock.On("UpdateExportSink", context1, updateExportSinkParams)}
}

func (_c *MockNamespaceClient_UpdateExportSink_Call) Run(run func(context1 context.Context, updateExportSinkParams namespace.UpdateExportSinkParams)) *MockNamespaceClient_UpdateExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.UpdateExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.UpdateExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_UpdateExportSink_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_UpdateExportSink_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_UpdateExportSink_Call) RunAndReturn(run func(context1 context.Context, updateExportSinkParams namespace.UpdateExportSinkParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_UpdateExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHA provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) UpdateHA(context1 context.Context, updateHAParams namespace.UpdateHAParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, updateHAParams)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHA")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateHAParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, updateHAParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateHAParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, updateHAParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.UpdateHAParams) error); ok {
		r1 = returnFunc(context1, updateHAParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_UpdateHA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHA'
type MockNamespaceClient_UpdateHA_Call struct {
	*mock.Call
}

// UpdateHA is a helper method to define mock.On call
//   - context1 context.Context
//   - updateHAParams namespace.UpdateHAParams
func (_e *MockNamespaceClient_Expecter) UpdateHA(context1 interface{}, updateHAParams interface{}) *MockNamespaceClient_UpdateHA_Call {
	return &MockNamespaceClient_UpdateHA_Call{Call: _e.mock.On("UpdateHA", context1, updateHAParams)}
}

func (_c *MockNamespaceClient_UpdateHA_Call) Run(run func(context1 context.Context, updateHAParams namespace.UpdateHAParams)) *MockNamespaceClient_UpdateHA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.UpdateHAParams
		if args[1] != nil {
			arg1 = args[1].(namespace.UpdateHAParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_UpdateHA_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_UpdateHA_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_UpdateHA_Call) RunAndReturn(run func(context1 context.Context, updateHAParams namespace.UpdateHAParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_UpdateHA_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespace provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) UpdateNamespace(context1 context.Context, updateNamespaceParams namespace.UpdateNamespaceParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, updateNamespaceParams)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespace")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateNamespaceParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, updateNamespaceParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.UpdateNamespaceParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, updateNamespaceParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.UpdateNamespaceParams) error); ok {
		r1 = returnFunc(context1, updateNamespaceParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_UpdateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespace'
type MockNamespaceClient_UpdateNamespace_Call struct {
	*mock.Call
}

// UpdateNamespace is a helper method to define mock.On call
//   - context1 context.Context
//   - updateNamespaceParams namespace.UpdateNamespaceParams
func (_e *MockNamespaceClient_Expecter) UpdateNamespace(context1 interface{}, updateNamespaceParams interface{}) *MockNamespaceClient_UpdateNamespace_Call {
	return &MockNamespaceClient_UpdateNamespace_Call{Call: _e.mock.On("UpdateNamespace", context1, updateNamespaceParams)}
}

func (_c *MockNamespaceClient_UpdateNamespace_Call) Run(run func(context1 context.Context, updateNamespaceParams namespace.UpdateNamespaceParams)) *MockNamespaceClient_UpdateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.UpdateNamespaceParams
		if args[1] != nil {
			arg1 = args[1].(namespace.UpdateNamespaceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_UpdateNamespace_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_UpdateNamespace_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_UpdateNamespace_Call) RunAndReturn(run func(context1 context.Context, updateNamespaceParams namespace.UpdateNamespaceParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_UpdateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateExportSink provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ValidateExportSink(context1 context.Context, validateExportSinkParams namespace.ValidateExportSinkParams) error {
	ret := _mock.Called(context1, validateExportSinkParams)

	if len(ret) == 0 {
		panic("no return value specified for ValidateExportSink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.ValidateExportSinkParams) error); ok {
		r0 = returnFunc(context1, validateExportSinkParams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNamespaceClient_ValidateExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateExportSink'
type MockNamespaceClient_ValidateExportSink_Call struct {
	*mock.Call
}

// ValidateExportSink is a helper method to define mock.On call
//   - context1 context.Context
//   - validateExportSinkParams namespace.ValidateExportSinkParams
func (_e *MockNamespaceClient_Expecter) ValidateExportSink(context1 interface{}, validateExportSinkParams interface{}) *MockNamespaceClient_ValidateExportSink_Call {
	return &MockNamespaceClient_ValidateExportSink_Call{Call: _e.mock.On("ValidateExportSink", context1, validateExportSinkParams)}
}

func (_c *MockNamespaceClient_ValidateExportSink_Call) Run(run func(context1 context.Context, validateExportSinkParams namespace.ValidateExportSinkParams)) *MockNamespaceClient_ValidateExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.ValidateExportSinkParams
		if args[1] != nil {
			arg1 = args[1].(namespace.ValidateExportSinkParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ValidateExportSink_Call) Return(err error) *MockNamespaceClient_ValidateExportSink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNamespaceClient_ValidateExportSink_Call) RunAndReturn(run func(context1 context.Context, validateExportSinkParams namespace.ValidateExportSinkParams) error) *MockNamespaceClient_ValidateExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPoller creates a new instance of MockPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoller {
	mock := &MockPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPoller is an autogenerated mock type for the Poller type
type MockPoller struct {
	mock.Mock
}

type MockPoller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoller) EXPECT() *MockPoller_Expecter {
	return &MockPoller_Expecter{mock: &_m.Mock}
}

// PollAsyncOperation provides a mock function for the type MockPoller
func (_mock *MockPoller) PollAsyncOperation(commandContext *temporalcloudcli.CommandContext, s string, s1 string) error {
	ret := _mock.Called(commandContext, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for PollAsyncOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*temporalcloudcli.CommandContext, string, string) error); ok {
		r0 = returnFunc(commandContext, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_PollAsyncOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollAsyncOperation'
type MockPoller_PollAsyncOperation_Call struct {
	*mock.Call
}

// PollAsyncOperation is a helper method to define mock.On call
//   - commandContext *temporalcloudcli.CommandContext
//   - s string
//   - s1 string
func (_e *MockPoller_Expecter) PollAsyncOperation(commandContext interface{}, s interface{}, s1 interface{}) *MockPoller_PollAsyncOperation_Call {
	return &MockPoller_PollAsyncOperation_Call{Call: _e.mock.On("PollAsyncOperation", commandContext, s, s1)}
}

func (_c *MockPoller_PollAsyncOperation_Call) Run(run func(commandContext *temporalcloudcli.CommandContext, s string, s1 string)) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *temporalcloudcli.CommandContext
		if args[0] != nil {
			arg0 = args[0].(*temporalcloudcli.CommandContext)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPoller_PollAsyncOperation_Call) Return(err error) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPoller_PollAsyncOperation_Call) RunAndReturn(run func(commandContext *temporalcloudcli.CommandContext, s string, s1 string) error) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAsyncOperationHandler creates a new instance of MockAsyncOperationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsyncOperationHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsyncOperationHandler {
	mock := &MockAsyncOperationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAsyncOperationHandler is an autogenerated mock type for the AsyncOperationHandler type
type MockAsyncOperationHandler struct {
	mock.Mock
}

type MockAsyncOperationHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsyncOperationHandler) EXPECT() *MockAsyncOperationHandler_Expecter {
	return &MockAsyncOperationHandler_Expecter{mock: &_m.Mock}
}

// HandleCreateErr provides a mock function for the type MockAsyncOperationHandler
func (_mock *MockAsyncOperationHandler) HandleCreateErr(err error) error {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for HandleCreateErr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(error) error); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAsyncOperationHandler_HandleCreateErr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreateErr'
type MockAsyncOperationHandler_HandleCreateErr_Call struct {
	*mock.Call
}

// HandleCreateErr is a helper method to define mock.On call
//   - err error
func (_e *MockAsyncOperationHandler_Expecter) HandleCreateErr(err interface{}) *MockAsyncOperationHandler_HandleCreateErr_Call {
	return &MockAsyncOperationHandler_HandleCreateErr_Call{Call: _e.mock.On("HandleCreateErr", err)}
}

func (_c *MockAsyncOperationHandler_HandleCreateErr_Call) Run(run func(err error)) *MockAsyncOperationHandler_HandleCreateErr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncOperationHandler_HandleCreateErr_Call) Return(err1 error) *MockAsyncOperationHandler_HandleCreateErr_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockAsyncOperationHandler_HandleCreateErr_Call) RunAndReturn(run func(err error) error) *MockAsyncOperationHandler_HandleCreateErr_Call {
	_c.Call.Return(run)
	return _c
}

// HandleDeleteErr provides a mock function for the type MockAsyncOperationHandler
func (_mock *MockAsyncOperationHandler) HandleDeleteErr(err error) error {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for HandleDeleteErr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(error) error); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAsyncOperationHandler_HandleDeleteErr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDeleteErr'
type MockAsyncOperationHandler_HandleDeleteErr_Call struct {
	*mock.Call
}

// HandleDeleteErr is a helper method to define mock.On call
//   - err error
func (_e *MockAsyncOperationHandler_Expecter) HandleDeleteErr(err interface{}) *MockAsyncOperationHandler_HandleDeleteErr_Call {
	return &MockAsyncOperationHandler_HandleDeleteErr_Call{Call: _e.mock.On("HandleDeleteErr", err)}
}

func (_c *MockAsyncOperationHandler_HandleDeleteErr_Call) Run(run func(err error)) *MockAsyncOperationHandler_HandleDeleteErr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncOperationHandler_HandleDeleteErr_Call) Return(err1 error) *MockAsyncOperationHandler_HandleDeleteErr_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockAsyncOperationHandler_HandleDeleteErr_Call) RunAndReturn(run func(err error) error) *MockAsyncOperationHandler_HandleDeleteErr_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOperation provides a mock function for the type MockAsyncOperationHandler
func (_mock *MockAsyncOperationHandler) HandleOperation(op *operation.AsyncOperation, id string) error {
	ret := _mock.Called(op, id)

	if len(ret) == 0 {
		panic("no return value specified for HandleOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*operation.AsyncOperation, string) error); ok {
		r0 = returnFunc(op, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAsyncOperationHandler_HandleOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOperation'
type MockAsyncOperationHandler_HandleOperation_Call struct {
	*mock.Call
}

// HandleOperation is a helper method to define mock.On call
//   - op *operation.AsyncOperation
//   - id string
func (_e *MockAsyncOperationHandler_Expecter) HandleOperation(op interface{}, id interface{}) *MockAsyncOperationHandler_HandleOperation_Call {
	return &MockAsyncOperationHandler_HandleOperation_Call{Call: _e.mock.On("HandleOperation", op, id)}
}

func (_c *MockAsyncOperationHandler_HandleOperation_Call) Run(run func(op *operation.AsyncOperation, id string)) *MockAsyncOperationHandler_HandleOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *operation.AsyncOperation
		if args[0] != nil {
			arg0 = args[0].(*operation.AsyncOperation)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncOperationHandler_HandleOperation_Call) Return(err error) *MockAsyncOperationHandler_HandleOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAsyncOperationHandler_HandleOperation_Call) RunAndReturn(run func(op *operation.AsyncOperation, id string) error) *MockAsyncOperationHandler_HandleOperation_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpdateErr provides a mock function for the type MockAsyncOperationHandler
func (_mock *MockAsyncOperationHandler) HandleUpdateErr(err error) error {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpdateErr")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(error) error); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAsyncOperationHandler_HandleUpdateErr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpdateErr'
type MockAsyncOperationHandler_HandleUpdateErr_Call struct {
	*mock.Call
}

// HandleUpdateErr is a helper method to define mock.On call
//   - err error
func (_e *MockAsyncOperationHandler_Expecter) HandleUpdateErr(err interface{}) *MockAsyncOperationHandler_HandleUpdateErr_Call {
	return &MockAsyncOperationHandler_HandleUpdateErr_Call{Call: _e.mock.On("HandleUpdateErr", err)}
}

func (_c *MockAsyncOperationHandler_HandleUpdateErr_Call) Run(run func(err error)) *MockAsyncOperationHandler_HandleUpdateErr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncOperationHandler_HandleUpdateErr_Call) Return(err1 error) *MockAsyncOperationHandler_HandleUpdateErr_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockAsyncOperationHandler_HandleUpdateErr_Call) RunAndReturn(run func(err error) error) *MockAsyncOperationHandler_HandleUpdateErr_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// PromptApply provides a mock function for the type MockPrompter
func (_mock *MockPrompter) PromptApply(old proto.Message, new proto.Message, verbose bool) error {
	ret := _mock.Called(old, new, verbose)

	if len(ret) == 0 {
		panic("no return value specified for PromptApply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(proto.Message, proto.Message, bool) error); ok {
		r0 = returnFunc(old, new, verbose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrompter_PromptApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptApply'
type MockPrompter_PromptApply_Call struct {
	*mock.Call
}

// PromptApply is a helper method to define mock.On call
//   - old proto.Message
//   - new proto.Message
//   - verbose bool
func (_e *MockPrompter_Expecter) PromptApply(old interface{}, new interface{}, verbose interface{}) *MockPrompter_PromptApply_Call {
	return &MockPrompter_PromptApply_Call{Call: _e.mock.On("PromptApply", old, new, verbose)}
}

func (_c *MockPrompter_PromptApply_Call) Run(run func(old proto.Message, new proto.Message, verbose bool)) *MockPrompter_PromptApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proto.Message
		if args[0] != nil {
			arg0 = args[0].(proto.Message)
		}
		var arg1 proto.Message
		if args[1] != nil {
			arg1 = args[1].(proto.Message)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_PromptApply_Call) Return(err error) *MockPrompter_PromptApply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrompter_PromptApply_Call) RunAndReturn(run func(old proto.Message, new proto.Message, verbose bool) error) *MockPrompter_PromptApply_Call {
	_c.Call.Return(run)
	return _c
}
