// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/temporalio/cloud-cli/internal/cert"
	"github.com/temporalio/cloud-cli/internal/namespace"
	"github.com/temporalio/cloud-cli/temporalcloudcli"
	namespace0 "go.temporal.io/cloud-sdk/api/namespace/v1"
	"go.temporal.io/cloud-sdk/api/operation/v1"
)

// NewMockNamespaceClient creates a new instance of MockNamespaceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNamespaceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNamespaceClient {
	mock := &MockNamespaceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNamespaceClient is an autogenerated mock type for the NamespaceClient type
type MockNamespaceClient struct {
	mock.Mock
}

type MockNamespaceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNamespaceClient) EXPECT() *MockNamespaceClient_Expecter {
	return &MockNamespaceClient_Expecter{mock: &_m.Mock}
}

// AddCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) AddCACerts(context1 context.Context, addCACertsParams namespace.AddCACertsParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, addCACertsParams)

	if len(ret) == 0 {
		panic("no return value specified for AddCACerts")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCACertsParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, addCACertsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.AddCACertsParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, addCACertsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.AddCACertsParams) error); ok {
		r1 = returnFunc(context1, addCACertsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_AddCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCACerts'
type MockNamespaceClient_AddCACerts_Call struct {
	*mock.Call
}

// AddCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - addCACertsParams namespace.AddCACertsParams
func (_e *MockNamespaceClient_Expecter) AddCACerts(context1 interface{}, addCACertsParams interface{}) *MockNamespaceClient_AddCACerts_Call {
	return &MockNamespaceClient_AddCACerts_Call{Call: _e.mock.On("AddCACerts", context1, addCACertsParams)}
}

func (_c *MockNamespaceClient_AddCACerts_Call) Run(run func(context1 context.Context, addCACertsParams namespace.AddCACertsParams)) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.AddCACertsParams
		if args[1] != nil {
			arg1 = args[1].(namespace.AddCACertsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_AddCACerts_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_AddCACerts_Call) RunAndReturn(run func(context1 context.Context, addCACertsParams namespace.AddCACertsParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_AddCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) DeleteCACerts(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams) (*operation.AsyncOperation, error) {
	ret := _mock.Called(context1, deleteCACertsParams)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCACerts")
	}

	var r0 *operation.AsyncOperation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCACertsParams) (*operation.AsyncOperation, error)); ok {
		return returnFunc(context1, deleteCACertsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, namespace.DeleteCACertsParams) *operation.AsyncOperation); ok {
		r0 = returnFunc(context1, deleteCACertsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operation.AsyncOperation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, namespace.DeleteCACertsParams) error); ok {
		r1 = returnFunc(context1, deleteCACertsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_DeleteCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCACerts'
type MockNamespaceClient_DeleteCACerts_Call struct {
	*mock.Call
}

// DeleteCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - deleteCACertsParams namespace.DeleteCACertsParams
func (_e *MockNamespaceClient_Expecter) DeleteCACerts(context1 interface{}, deleteCACertsParams interface{}) *MockNamespaceClient_DeleteCACerts_Call {
	return &MockNamespaceClient_DeleteCACerts_Call{Call: _e.mock.On("DeleteCACerts", context1, deleteCACertsParams)}
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) Run(run func(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams)) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 namespace.DeleteCACertsParams
		if args[1] != nil {
			arg1 = args[1].(namespace.DeleteCACertsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) Return(asyncOperation *operation.AsyncOperation, err error) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Return(asyncOperation, err)
	return _c
}

func (_c *MockNamespaceClient_DeleteCACerts_Call) RunAndReturn(run func(context1 context.Context, deleteCACertsParams namespace.DeleteCACertsParams) (*operation.AsyncOperation, error)) *MockNamespaceClient_DeleteCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) GetNamespace(context1 context.Context, s string) (*namespace0.Namespace, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *namespace0.Namespace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*namespace0.Namespace, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *namespace0.Namespace); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*namespace0.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockNamespaceClient_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) GetNamespace(context1 interface{}, s interface{}) *MockNamespaceClient_GetNamespace_Call {
	return &MockNamespaceClient_GetNamespace_Call{Call: _e.mock.On("GetNamespace", context1, s)}
}

func (_c *MockNamespaceClient_GetNamespace_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_GetNamespace_Call) Return(namespace1 *namespace0.Namespace, err error) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Return(namespace1, err)
	return _c
}

func (_c *MockNamespaceClient_GetNamespace_Call) RunAndReturn(run func(context1 context.Context, s string) (*namespace0.Namespace, error)) *MockNamespaceClient_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// ListCACerts provides a mock function for the type MockNamespaceClient
func (_mock *MockNamespaceClient) ListCACerts(context1 context.Context, s string) ([]cert.CACert, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for ListCACerts")
	}

	var r0 []cert.CACert
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]cert.CACert, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []cert.CACert); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cert.CACert)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNamespaceClient_ListCACerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCACerts'
type MockNamespaceClient_ListCACerts_Call struct {
	*mock.Call
}

// ListCACerts is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockNamespaceClient_Expecter) ListCACerts(context1 interface{}, s interface{}) *MockNamespaceClient_ListCACerts_Call {
	return &MockNamespaceClient_ListCACerts_Call{Call: _e.mock.On("ListCACerts", context1, s)}
}

func (_c *MockNamespaceClient_ListCACerts_Call) Run(run func(context1 context.Context, s string)) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNamespaceClient_ListCACerts_Call) Return(cACerts []cert.CACert, err error) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Return(cACerts, err)
	return _c
}

func (_c *MockNamespaceClient_ListCACerts_Call) RunAndReturn(run func(context1 context.Context, s string) ([]cert.CACert, error)) *MockNamespaceClient_ListCACerts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPoller creates a new instance of MockPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoller {
	mock := &MockPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPoller is an autogenerated mock type for the Poller type
type MockPoller struct {
	mock.Mock
}

type MockPoller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoller) EXPECT() *MockPoller_Expecter {
	return &MockPoller_Expecter{mock: &_m.Mock}
}

// PollAsyncOperation provides a mock function for the type MockPoller
func (_mock *MockPoller) PollAsyncOperation(commandContext *temporalcloudcli.CommandContext, s string, s1 string) error {
	ret := _mock.Called(commandContext, s, s1)

	if len(ret) == 0 {
		panic("no return value specified for PollAsyncOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*temporalcloudcli.CommandContext, string, string) error); ok {
		r0 = returnFunc(commandContext, s, s1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_PollAsyncOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollAsyncOperation'
type MockPoller_PollAsyncOperation_Call struct {
	*mock.Call
}

// PollAsyncOperation is a helper method to define mock.On call
//   - commandContext *temporalcloudcli.CommandContext
//   - s string
//   - s1 string
func (_e *MockPoller_Expecter) PollAsyncOperation(commandContext interface{}, s interface{}, s1 interface{}) *MockPoller_PollAsyncOperation_Call {
	return &MockPoller_PollAsyncOperation_Call{Call: _e.mock.On("PollAsyncOperation", commandContext, s, s1)}
}

func (_c *MockPoller_PollAsyncOperation_Call) Run(run func(commandContext *temporalcloudcli.CommandContext, s string, s1 string)) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *temporalcloudcli.CommandContext
		if args[0] != nil {
			arg0 = args[0].(*temporalcloudcli.CommandContext)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPoller_PollAsyncOperation_Call) Return(err error) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPoller_PollAsyncOperation_Call) RunAndReturn(run func(commandContext *temporalcloudcli.CommandContext, s string, s1 string) error) *MockPoller_PollAsyncOperation_Call {
	_c.Call.Return(run)
	return _c
}
