dir: "{{ .InterfaceDir }}/mock"
filename: mock.go
pkgname: mock
packages:
  github.com/temporalio/cloud-cli/temporalcloudcli:
    interfaces:
      Poller:
      NamespaceClient:
      AsyncOperationHandler:
      ApplyPrompter:
  github.com/temporalio/cloud-cli/internal/namespace:
    interfaces:
      CloudService:
