// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/temporalio/cloud-cli/temporalcloudcli/async"
)

// NewMockPoller creates a new instance of MockPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPoller {
	mock := &MockPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPoller is an autogenerated mock type for the Poller type
type MockPoller struct {
	mock.Mock
}

type MockPoller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoller) EXPECT() *MockPoller_Expecter {
	return &MockPoller_Expecter{mock: &_m.Mock}
}

// AwaitAsyncOperation provides a mock function for the type MockPoller
func (_mock *MockPoller) AwaitAsyncOperation(ctx context.Context, asyncOpID string) error {
	ret := _mock.Called(ctx, asyncOpID)

	if len(ret) == 0 {
		panic("no return value specified for AwaitAsyncOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, asyncOpID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_AwaitAsyncOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwaitAsyncOperation'
type MockPoller_AwaitAsyncOperation_Call struct {
	*mock.Call
}

// AwaitAsyncOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - asyncOpID string
func (_e *MockPoller_Expecter) AwaitAsyncOperation(ctx interface{}, asyncOpID interface{}) *MockPoller_AwaitAsyncOperation_Call {
	return &MockPoller_AwaitAsyncOperation_Call{Call: _e.mock.On("AwaitAsyncOperation", ctx, asyncOpID)}
}

func (_c *MockPoller_AwaitAsyncOperation_Call) Run(run func(ctx context.Context, asyncOpID string)) *MockPoller_AwaitAsyncOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPoller_AwaitAsyncOperation_Call) Return(err error) *MockPoller_AwaitAsyncOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPoller_AwaitAsyncOperation_Call) RunAndReturn(run func(ctx context.Context, asyncOpID string) error) *MockPoller_AwaitAsyncOperation_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCreateAsyncOperationResponse provides a mock function for the type MockPoller
func (_mock *MockPoller) HandleCreateAsyncOperationResponse(ctx context.Context, response async.RespWithAsyncOp, err error) error {
	ret := _mock.Called(ctx, response, err)

	if len(ret) == 0 {
		panic("no return value specified for HandleCreateAsyncOperationResponse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, async.RespWithAsyncOp, error) error); ok {
		r0 = returnFunc(ctx, response, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_HandleCreateAsyncOperationResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreateAsyncOperationResponse'
type MockPoller_HandleCreateAsyncOperationResponse_Call struct {
	*mock.Call
}

// HandleCreateAsyncOperationResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - response async.RespWithAsyncOp
//   - err error
func (_e *MockPoller_Expecter) HandleCreateAsyncOperationResponse(ctx interface{}, response interface{}, err interface{}) *MockPoller_HandleCreateAsyncOperationResponse_Call {
	return &MockPoller_HandleCreateAsyncOperationResponse_Call{Call: _e.mock.On("HandleCreateAsyncOperationResponse", ctx, response, err)}
}

func (_c *MockPoller_HandleCreateAsyncOperationResponse_Call) Run(run func(ctx context.Context, response async.RespWithAsyncOp, err error)) *MockPoller_HandleCreateAsyncOperationResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 async.RespWithAsyncOp
		if args[1] != nil {
			arg1 = args[1].(async.RespWithAsyncOp)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPoller_HandleCreateAsyncOperationResponse_Call) Return(err1 error) *MockPoller_HandleCreateAsyncOperationResponse_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockPoller_HandleCreateAsyncOperationResponse_Call) RunAndReturn(run func(ctx context.Context, response async.RespWithAsyncOp, err error) error) *MockPoller_HandleCreateAsyncOperationResponse_Call {
	_c.Call.Return(run)
	return _c
}

// HandleDeleteOperation provides a mock function for the type MockPoller
func (_mock *MockPoller) HandleDeleteOperation(ctx context.Context, response async.RespWithAsyncOp, err error) error {
	ret := _mock.Called(ctx, response, err)

	if len(ret) == 0 {
		panic("no return value specified for HandleDeleteOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, async.RespWithAsyncOp, error) error); ok {
		r0 = returnFunc(ctx, response, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_HandleDeleteOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDeleteOperation'
type MockPoller_HandleDeleteOperation_Call struct {
	*mock.Call
}

// HandleDeleteOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - response async.RespWithAsyncOp
//   - err error
func (_e *MockPoller_Expecter) HandleDeleteOperation(ctx interface{}, response interface{}, err interface{}) *MockPoller_HandleDeleteOperation_Call {
	return &MockPoller_HandleDeleteOperation_Call{Call: _e.mock.On("HandleDeleteOperation", ctx, response, err)}
}

func (_c *MockPoller_HandleDeleteOperation_Call) Run(run func(ctx context.Context, response async.RespWithAsyncOp, err error)) *MockPoller_HandleDeleteOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 async.RespWithAsyncOp
		if args[1] != nil {
			arg1 = args[1].(async.RespWithAsyncOp)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPoller_HandleDeleteOperation_Call) Return(err1 error) *MockPoller_HandleDeleteOperation_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockPoller_HandleDeleteOperation_Call) RunAndReturn(run func(ctx context.Context, response async.RespWithAsyncOp, err error) error) *MockPoller_HandleDeleteOperation_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpdateOperation provides a mock function for the type MockPoller
func (_mock *MockPoller) HandleUpdateOperation(ctx context.Context, response async.RespWithAsyncOp, err error) error {
	ret := _mock.Called(ctx, response, err)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpdateOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, async.RespWithAsyncOp, error) error); ok {
		r0 = returnFunc(ctx, response, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_HandleUpdateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpdateOperation'
type MockPoller_HandleUpdateOperation_Call struct {
	*mock.Call
}

// HandleUpdateOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - response async.RespWithAsyncOp
//   - err error
func (_e *MockPoller_Expecter) HandleUpdateOperation(ctx interface{}, response interface{}, err interface{}) *MockPoller_HandleUpdateOperation_Call {
	return &MockPoller_HandleUpdateOperation_Call{Call: _e.mock.On("HandleUpdateOperation", ctx, response, err)}
}

func (_c *MockPoller_HandleUpdateOperation_Call) Run(run func(ctx context.Context, response async.RespWithAsyncOp, err error)) *MockPoller_HandleUpdateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 async.RespWithAsyncOp
		if args[1] != nil {
			arg1 = args[1].(async.RespWithAsyncOp)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPoller_HandleUpdateOperation_Call) Return(err1 error) *MockPoller_HandleUpdateOperation_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockPoller_HandleUpdateOperation_Call) RunAndReturn(run func(ctx context.Context, response async.RespWithAsyncOp, err error) error) *MockPoller_HandleUpdateOperation_Call {
	_c.Call.Return(run)
	return _c
}
