// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/proto"
)

// NewMockEditor creates a new instance of MockEditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditor {
	mock := &MockEditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEditor is an autogenerated mock type for the Editor type
type MockEditor struct {
	mock.Mock
}

type MockEditor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditor) EXPECT() *MockEditor_Expecter {
	return &MockEditor_Expecter{mock: &_m.Mock}
}

// EditProto provides a mock function for the type MockEditor
func (_mock *MockEditor) EditProto(existing proto.Message) (proto.Message, error) {
	ret := _mock.Called(existing)

	if len(ret) == 0 {
		panic("no return value specified for EditProto")
	}

	var r0 proto.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(proto.Message) (proto.Message, error)); ok {
		return returnFunc(existing)
	}
	if returnFunc, ok := ret.Get(0).(func(proto.Message) proto.Message); ok {
		r0 = returnFunc(existing)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(proto.Message) error); ok {
		r1 = returnFunc(existing)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEditor_EditProto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditProto'
type MockEditor_EditProto_Call struct {
	*mock.Call
}

// EditProto is a helper method to define mock.On call
//   - existing proto.Message
func (_e *MockEditor_Expecter) EditProto(existing interface{}) *MockEditor_EditProto_Call {
	return &MockEditor_EditProto_Call{Call: _e.mock.On("EditProto", existing)}
}

func (_c *MockEditor_EditProto_Call) Run(run func(existing proto.Message)) *MockEditor_EditProto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proto.Message
		if args[0] != nil {
			arg0 = args[0].(proto.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEditor_EditProto_Call) Return(v proto.Message, err error) *MockEditor_EditProto_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockEditor_EditProto_Call) RunAndReturn(run func(existing proto.Message) (proto.Message, error)) *MockEditor_EditProto_Call {
	_c.Call.Return(run)
	return _c
}
