// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/cloud-sdk/api/cloudservice/v1"
	"google.golang.org/grpc"
)

// NewMockCloudService creates a new instance of MockCloudService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudService {
	mock := &MockCloudService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudService is an autogenerated mock type for the CloudService type
type MockCloudService struct {
	mock.Mock
}

type MockCloudService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudService) EXPECT() *MockCloudService_Expecter {
	return &MockCloudService_Expecter{mock: &_m.Mock}
}

// AddNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) AddNamespaceRegion(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddNamespaceRegion")
	}

	var r0 *cloudservice.AddNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.AddNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.AddNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_AddNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNamespaceRegion'
type MockCloudService_AddNamespaceRegion_Call struct {
	*mock.Call
}

// AddNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.AddNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) AddNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_AddNamespaceRegion_Call {
	return &MockCloudService_AddNamespaceRegion_Call{Call: _e.mock.On("AddNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_AddNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.AddNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.AddNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_AddNamespaceRegion_Call) Return(addNamespaceRegionResponse *cloudservice.AddNamespaceRegionResponse, err error) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Return(addNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_AddNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error)) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNamespaceExportSink provides a mock function for the type MockCloudService
func (_mock *MockCloudService) CreateNamespaceExportSink(ctx context.Context, req *cloudservice.CreateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.CreateNamespaceExportSinkResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespaceExportSink")
	}

	var r0 *cloudservice.CreateNamespaceExportSinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.CreateNamespaceExportSinkRequest, ...grpc.CallOption) (*cloudservice.CreateNamespaceExportSinkResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.CreateNamespaceExportSinkRequest, ...grpc.CallOption) *cloudservice.CreateNamespaceExportSinkResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.CreateNamespaceExportSinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.CreateNamespaceExportSinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_CreateNamespaceExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNamespaceExportSink'
type MockCloudService_CreateNamespaceExportSink_Call struct {
	*mock.Call
}

// CreateNamespaceExportSink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.CreateNamespaceExportSinkRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) CreateNamespaceExportSink(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_CreateNamespaceExportSink_Call {
	return &MockCloudService_CreateNamespaceExportSink_Call{Call: _e.mock.On("CreateNamespaceExportSink",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_CreateNamespaceExportSink_Call) Run(run func(ctx context.Context, req *cloudservice.CreateNamespaceExportSinkRequest, opts ...grpc.CallOption)) *MockCloudService_CreateNamespaceExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.CreateNamespaceExportSinkRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.CreateNamespaceExportSinkRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_CreateNamespaceExportSink_Call) Return(createNamespaceExportSinkResponse *cloudservice.CreateNamespaceExportSinkResponse, err error) *MockCloudService_CreateNamespaceExportSink_Call {
	_c.Call.Return(createNamespaceExportSinkResponse, err)
	return _c
}

func (_c *MockCloudService_CreateNamespaceExportSink_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.CreateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.CreateNamespaceExportSinkResponse, error)) *MockCloudService_CreateNamespaceExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNamespaceExportSink provides a mock function for the type MockCloudService
func (_mock *MockCloudService) DeleteNamespaceExportSink(ctx context.Context, req *cloudservice.DeleteNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceExportSinkResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceExportSink")
	}

	var r0 *cloudservice.DeleteNamespaceExportSinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceExportSinkRequest, ...grpc.CallOption) (*cloudservice.DeleteNamespaceExportSinkResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceExportSinkRequest, ...grpc.CallOption) *cloudservice.DeleteNamespaceExportSinkResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.DeleteNamespaceExportSinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.DeleteNamespaceExportSinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_DeleteNamespaceExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespaceExportSink'
type MockCloudService_DeleteNamespaceExportSink_Call struct {
	*mock.Call
}

// DeleteNamespaceExportSink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.DeleteNamespaceExportSinkRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) DeleteNamespaceExportSink(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_DeleteNamespaceExportSink_Call {
	return &MockCloudService_DeleteNamespaceExportSink_Call{Call: _e.mock.On("DeleteNamespaceExportSink",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_DeleteNamespaceExportSink_Call) Run(run func(ctx context.Context, req *cloudservice.DeleteNamespaceExportSinkRequest, opts ...grpc.CallOption)) *MockCloudService_DeleteNamespaceExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.DeleteNamespaceExportSinkRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.DeleteNamespaceExportSinkRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_DeleteNamespaceExportSink_Call) Return(deleteNamespaceExportSinkResponse *cloudservice.DeleteNamespaceExportSinkResponse, err error) *MockCloudService_DeleteNamespaceExportSink_Call {
	_c.Call.Return(deleteNamespaceExportSinkResponse, err)
	return _c
}

func (_c *MockCloudService_DeleteNamespaceExportSink_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.DeleteNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceExportSinkResponse, error)) *MockCloudService_DeleteNamespaceExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) DeleteNamespaceRegion(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceRegion")
	}

	var r0 *cloudservice.DeleteNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.DeleteNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.DeleteNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_DeleteNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespaceRegion'
type MockCloudService_DeleteNamespaceRegion_Call struct {
	*mock.Call
}

// DeleteNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.DeleteNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) DeleteNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_DeleteNamespaceRegion_Call {
	return &MockCloudService_DeleteNamespaceRegion_Call{Call: _e.mock.On("DeleteNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.DeleteNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.DeleteNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) Return(deleteNamespaceRegionResponse *cloudservice.DeleteNamespaceRegionResponse, err error) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Return(deleteNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error)) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// FailoverNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) FailoverNamespaceRegion(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FailoverNamespaceRegion")
	}

	var r0 *cloudservice.FailoverNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.FailoverNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.FailoverNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_FailoverNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailoverNamespaceRegion'
type MockCloudService_FailoverNamespaceRegion_Call struct {
	*mock.Call
}

// FailoverNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.FailoverNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) FailoverNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_FailoverNamespaceRegion_Call {
	return &MockCloudService_FailoverNamespaceRegion_Call{Call: _e.mock.On("FailoverNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.FailoverNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.FailoverNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) Return(failoverNamespaceRegionResponse *cloudservice.FailoverNamespaceRegionResponse, err error) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Return(failoverNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error)) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespace(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *cloudservice.GetNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) *cloudservice.GetNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockCloudService_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespace_Call {
	return &MockCloudService_GetNamespace_Call{Call: _e.mock.On("GetNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) Return(getNamespaceResponse *cloudservice.GetNamespaceResponse, err error) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(getNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaceExportSink provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespaceExportSink(ctx context.Context, req *cloudservice.GetNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinkResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceExportSink")
	}

	var r0 *cloudservice.GetNamespaceExportSinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceExportSinkRequest, ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinkResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceExportSinkRequest, ...grpc.CallOption) *cloudservice.GetNamespaceExportSinkResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespaceExportSinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespaceExportSinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespaceExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaceExportSink'
type MockCloudService_GetNamespaceExportSink_Call struct {
	*mock.Call
}

// GetNamespaceExportSink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespaceExportSinkRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespaceExportSink(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespaceExportSink_Call {
	return &MockCloudService_GetNamespaceExportSink_Call{Call: _e.mock.On("GetNamespaceExportSink",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespaceExportSink_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespaceExportSinkRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespaceExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespaceExportSinkRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespaceExportSinkRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespaceExportSink_Call) Return(getNamespaceExportSinkResponse *cloudservice.GetNamespaceExportSinkResponse, err error) *MockCloudService_GetNamespaceExportSink_Call {
	_c.Call.Return(getNamespaceExportSinkResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespaceExportSink_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinkResponse, error)) *MockCloudService_GetNamespaceExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaceExportSinks provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespaceExportSinks(ctx context.Context, req *cloudservice.GetNamespaceExportSinksRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinksResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceExportSinks")
	}

	var r0 *cloudservice.GetNamespaceExportSinksResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceExportSinksRequest, ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinksResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceExportSinksRequest, ...grpc.CallOption) *cloudservice.GetNamespaceExportSinksResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespaceExportSinksResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespaceExportSinksRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespaceExportSinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaceExportSinks'
type MockCloudService_GetNamespaceExportSinks_Call struct {
	*mock.Call
}

// GetNamespaceExportSinks is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespaceExportSinksRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespaceExportSinks(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespaceExportSinks_Call {
	return &MockCloudService_GetNamespaceExportSinks_Call{Call: _e.mock.On("GetNamespaceExportSinks",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespaceExportSinks_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespaceExportSinksRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespaceExportSinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespaceExportSinksRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespaceExportSinksRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespaceExportSinks_Call) Return(getNamespaceExportSinksResponse *cloudservice.GetNamespaceExportSinksResponse, err error) *MockCloudService_GetNamespaceExportSinks_Call {
	_c.Call.Return(getNamespaceExportSinksResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespaceExportSinks_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespaceExportSinksRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceExportSinksResponse, error)) *MockCloudService_GetNamespaceExportSinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaces provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespaces(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaces")
	}

	var r0 *cloudservice.GetNamespacesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) *cloudservice.GetNamespacesResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespacesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaces'
type MockCloudService_GetNamespaces_Call struct {
	*mock.Call
}

// GetNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespacesRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespaces(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespaces_Call {
	return &MockCloudService_GetNamespaces_Call{Call: _e.mock.On("GetNamespaces",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespaces_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespacesRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespacesRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) Return(getNamespacesResponse *cloudservice.GetNamespacesResponse, err error) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(getNamespacesResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// RenameCustomSearchAttribute provides a mock function for the type MockCloudService
func (_mock *MockCloudService) RenameCustomSearchAttribute(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RenameCustomSearchAttribute")
	}

	var r0 *cloudservice.RenameCustomSearchAttributeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) *cloudservice.RenameCustomSearchAttributeResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.RenameCustomSearchAttributeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_RenameCustomSearchAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameCustomSearchAttribute'
type MockCloudService_RenameCustomSearchAttribute_Call struct {
	*mock.Call
}

// RenameCustomSearchAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.RenameCustomSearchAttributeRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) RenameCustomSearchAttribute(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_RenameCustomSearchAttribute_Call {
	return &MockCloudService_RenameCustomSearchAttribute_Call{Call: _e.mock.On("RenameCustomSearchAttribute",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Run(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.RenameCustomSearchAttributeRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.RenameCustomSearchAttributeRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Return(renameCustomSearchAttributeResponse *cloudservice.RenameCustomSearchAttributeResponse, err error) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(renameCustomSearchAttributeResponse, err)
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespace(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespace")
	}

	var r0 *cloudservice.UpdateNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespace'
type MockCloudService_UpdateNamespace_Call struct {
	*mock.Call
}

// UpdateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespace_Call {
	return &MockCloudService_UpdateNamespace_Call{Call: _e.mock.On("UpdateNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) Return(updateNamespaceResponse *cloudservice.UpdateNamespaceResponse, err error) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(updateNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespaceExportSink provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespaceExportSink(ctx context.Context, req *cloudservice.UpdateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceExportSinkResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespaceExportSink")
	}

	var r0 *cloudservice.UpdateNamespaceExportSinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceExportSinkRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceExportSinkResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceExportSinkRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceExportSinkResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceExportSinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceExportSinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespaceExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespaceExportSink'
type MockCloudService_UpdateNamespaceExportSink_Call struct {
	*mock.Call
}

// UpdateNamespaceExportSink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceExportSinkRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespaceExportSink(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespaceExportSink_Call {
	return &MockCloudService_UpdateNamespaceExportSink_Call{Call: _e.mock.On("UpdateNamespaceExportSink",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespaceExportSink_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceExportSinkRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespaceExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceExportSinkRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceExportSinkRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespaceExportSink_Call) Return(updateNamespaceExportSinkResponse *cloudservice.UpdateNamespaceExportSinkResponse, err error) *MockCloudService_UpdateNamespaceExportSink_Call {
	_c.Call.Return(updateNamespaceExportSinkResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespaceExportSink_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceExportSinkResponse, error)) *MockCloudService_UpdateNamespaceExportSink_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespaceTags provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespaceTags(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespaceTags")
	}

	var r0 *cloudservice.UpdateNamespaceTagsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceTagsResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceTagsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespaceTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespaceTags'
type MockCloudService_UpdateNamespaceTags_Call struct {
	*mock.Call
}

// UpdateNamespaceTags is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceTagsRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespaceTags(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespaceTags_Call {
	return &MockCloudService_UpdateNamespaceTags_Call{Call: _e.mock.On("UpdateNamespaceTags",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceTagsRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceTagsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) Return(updateNamespaceTagsResponse *cloudservice.UpdateNamespaceTagsResponse, err error) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Return(updateNamespaceTagsResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error)) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateNamespaceExportSink provides a mock function for the type MockCloudService
func (_mock *MockCloudService) ValidateNamespaceExportSink(ctx context.Context, req *cloudservice.ValidateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.ValidateNamespaceExportSinkResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ValidateNamespaceExportSink")
	}

	var r0 *cloudservice.ValidateNamespaceExportSinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.ValidateNamespaceExportSinkRequest, ...grpc.CallOption) (*cloudservice.ValidateNamespaceExportSinkResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.ValidateNamespaceExportSinkRequest, ...grpc.CallOption) *cloudservice.ValidateNamespaceExportSinkResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.ValidateNamespaceExportSinkResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.ValidateNamespaceExportSinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_ValidateNamespaceExportSink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateNamespaceExportSink'
type MockCloudService_ValidateNamespaceExportSink_Call struct {
	*mock.Call
}

// ValidateNamespaceExportSink is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.ValidateNamespaceExportSinkRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) ValidateNamespaceExportSink(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_ValidateNamespaceExportSink_Call {
	return &MockCloudService_ValidateNamespaceExportSink_Call{Call: _e.mock.On("ValidateNamespaceExportSink",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_ValidateNamespaceExportSink_Call) Run(run func(ctx context.Context, req *cloudservice.ValidateNamespaceExportSinkRequest, opts ...grpc.CallOption)) *MockCloudService_ValidateNamespaceExportSink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.ValidateNamespaceExportSinkRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.ValidateNamespaceExportSinkRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_ValidateNamespaceExportSink_Call) Return(validateNamespaceExportSinkResponse *cloudservice.ValidateNamespaceExportSinkResponse, err error) *MockCloudService_ValidateNamespaceExportSink_Call {
	_c.Call.Return(validateNamespaceExportSinkResponse, err)
	return _c
}

func (_c *MockCloudService_ValidateNamespaceExportSink_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.ValidateNamespaceExportSinkRequest, opts ...grpc.CallOption) (*cloudservice.ValidateNamespaceExportSinkResponse, error)) *MockCloudService_ValidateNamespaceExportSink_Call {
	_c.Call.Return(run)
	return _c
}
