// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/cloud-sdk/api/cloudservice/v1"
	"google.golang.org/grpc"
)

// NewMockCloudService creates a new instance of MockCloudService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudService {
	mock := &MockCloudService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudService is an autogenerated mock type for the CloudService type
type MockCloudService struct {
	mock.Mock
}

type MockCloudService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudService) EXPECT() *MockCloudService_Expecter {
	return &MockCloudService_Expecter{mock: &_m.Mock}
}

// AddNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) AddNamespaceRegion(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddNamespaceRegion")
	}

	var r0 *cloudservice.AddNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.AddNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.AddNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.AddNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_AddNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNamespaceRegion'
type MockCloudService_AddNamespaceRegion_Call struct {
	*mock.Call
}

// AddNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.AddNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) AddNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_AddNamespaceRegion_Call {
	return &MockCloudService_AddNamespaceRegion_Call{Call: _e.mock.On("AddNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_AddNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.AddNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.AddNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_AddNamespaceRegion_Call) Return(addNamespaceRegionResponse *cloudservice.AddNamespaceRegionResponse, err error) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Return(addNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_AddNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.AddNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.AddNamespaceRegionResponse, error)) *MockCloudService_AddNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) CreateNamespace(ctx context.Context, req *cloudservice.CreateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.CreateNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespace")
	}

	var r0 *cloudservice.CreateNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.CreateNamespaceRequest, ...grpc.CallOption) (*cloudservice.CreateNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.CreateNamespaceRequest, ...grpc.CallOption) *cloudservice.CreateNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.CreateNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.CreateNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_CreateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNamespace'
type MockCloudService_CreateNamespace_Call struct {
	*mock.Call
}

// CreateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.CreateNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) CreateNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_CreateNamespace_Call {
	return &MockCloudService_CreateNamespace_Call{Call: _e.mock.On("CreateNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_CreateNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.CreateNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_CreateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.CreateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.CreateNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_CreateNamespace_Call) Return(createNamespaceResponse *cloudservice.CreateNamespaceResponse, err error) *MockCloudService_CreateNamespace_Call {
	_c.Call.Return(createNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_CreateNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.CreateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.CreateNamespaceResponse, error)) *MockCloudService_CreateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) DeleteNamespace(ctx context.Context, req *cloudservice.DeleteNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespace")
	}

	var r0 *cloudservice.DeleteNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRequest, ...grpc.CallOption) (*cloudservice.DeleteNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRequest, ...grpc.CallOption) *cloudservice.DeleteNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.DeleteNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.DeleteNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_DeleteNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespace'
type MockCloudService_DeleteNamespace_Call struct {
	*mock.Call
}

// DeleteNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.DeleteNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) DeleteNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_DeleteNamespace_Call {
	return &MockCloudService_DeleteNamespace_Call{Call: _e.mock.On("DeleteNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_DeleteNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_DeleteNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.DeleteNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.DeleteNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_DeleteNamespace_Call) Return(deleteNamespaceResponse *cloudservice.DeleteNamespaceResponse, err error) *MockCloudService_DeleteNamespace_Call {
	_c.Call.Return(deleteNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_DeleteNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceResponse, error)) *MockCloudService_DeleteNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) DeleteNamespaceRegion(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceRegion")
	}

	var r0 *cloudservice.DeleteNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.DeleteNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.DeleteNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.DeleteNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_DeleteNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespaceRegion'
type MockCloudService_DeleteNamespaceRegion_Call struct {
	*mock.Call
}

// DeleteNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.DeleteNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) DeleteNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_DeleteNamespaceRegion_Call {
	return &MockCloudService_DeleteNamespaceRegion_Call{Call: _e.mock.On("DeleteNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.DeleteNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.DeleteNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) Return(deleteNamespaceRegionResponse *cloudservice.DeleteNamespaceRegionResponse, err error) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Return(deleteNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_DeleteNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.DeleteNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.DeleteNamespaceRegionResponse, error)) *MockCloudService_DeleteNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// FailoverNamespaceRegion provides a mock function for the type MockCloudService
func (_mock *MockCloudService) FailoverNamespaceRegion(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FailoverNamespaceRegion")
	}

	var r0 *cloudservice.FailoverNamespaceRegionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) *cloudservice.FailoverNamespaceRegionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.FailoverNamespaceRegionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.FailoverNamespaceRegionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_FailoverNamespaceRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailoverNamespaceRegion'
type MockCloudService_FailoverNamespaceRegion_Call struct {
	*mock.Call
}

// FailoverNamespaceRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.FailoverNamespaceRegionRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) FailoverNamespaceRegion(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_FailoverNamespaceRegion_Call {
	return &MockCloudService_FailoverNamespaceRegion_Call{Call: _e.mock.On("FailoverNamespaceRegion",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) Run(run func(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption)) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.FailoverNamespaceRegionRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.FailoverNamespaceRegionRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) Return(failoverNamespaceRegionResponse *cloudservice.FailoverNamespaceRegionResponse, err error) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Return(failoverNamespaceRegionResponse, err)
	return _c
}

func (_c *MockCloudService_FailoverNamespaceRegion_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.FailoverNamespaceRegionRequest, opts ...grpc.CallOption) (*cloudservice.FailoverNamespaceRegionResponse, error)) *MockCloudService_FailoverNamespaceRegion_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespace(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *cloudservice.GetNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) *cloudservice.GetNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockCloudService_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespace_Call {
	return &MockCloudService_GetNamespace_Call{Call: _e.mock.On("GetNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) Return(getNamespaceResponse *cloudservice.GetNamespaceResponse, err error) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(getNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaces provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespaces(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaces")
	}

	var r0 *cloudservice.GetNamespacesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) *cloudservice.GetNamespacesResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespacesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaces'
type MockCloudService_GetNamespaces_Call struct {
	*mock.Call
}

// GetNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespacesRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespaces(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespaces_Call {
	return &MockCloudService_GetNamespaces_Call{Call: _e.mock.On("GetNamespaces",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespaces_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespacesRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespacesRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) Return(getNamespacesResponse *cloudservice.GetNamespacesResponse, err error) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(getNamespacesResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// RenameCustomSearchAttribute provides a mock function for the type MockCloudService
func (_mock *MockCloudService) RenameCustomSearchAttribute(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RenameCustomSearchAttribute")
	}

	var r0 *cloudservice.RenameCustomSearchAttributeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) *cloudservice.RenameCustomSearchAttributeResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.RenameCustomSearchAttributeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_RenameCustomSearchAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameCustomSearchAttribute'
type MockCloudService_RenameCustomSearchAttribute_Call struct {
	*mock.Call
}

// RenameCustomSearchAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.RenameCustomSearchAttributeRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) RenameCustomSearchAttribute(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_RenameCustomSearchAttribute_Call {
	return &MockCloudService_RenameCustomSearchAttribute_Call{Call: _e.mock.On("RenameCustomSearchAttribute",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Run(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.RenameCustomSearchAttributeRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.RenameCustomSearchAttributeRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Return(renameCustomSearchAttributeResponse *cloudservice.RenameCustomSearchAttributeResponse, err error) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(renameCustomSearchAttributeResponse, err)
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespace(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespace")
	}

	var r0 *cloudservice.UpdateNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespace'
type MockCloudService_UpdateNamespace_Call struct {
	*mock.Call
}

// UpdateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespace_Call {
	return &MockCloudService_UpdateNamespace_Call{Call: _e.mock.On("UpdateNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) Return(updateNamespaceResponse *cloudservice.UpdateNamespaceResponse, err error) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(updateNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespaceTags provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespaceTags(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespaceTags")
	}

	var r0 *cloudservice.UpdateNamespaceTagsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceTagsResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceTagsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceTagsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespaceTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespaceTags'
type MockCloudService_UpdateNamespaceTags_Call struct {
	*mock.Call
}

// UpdateNamespaceTags is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceTagsRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespaceTags(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespaceTags_Call {
	return &MockCloudService_UpdateNamespaceTags_Call{Call: _e.mock.On("UpdateNamespaceTags",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceTagsRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceTagsRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) Return(updateNamespaceTagsResponse *cloudservice.UpdateNamespaceTagsResponse, err error) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Return(updateNamespaceTagsResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespaceTags_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceTagsRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceTagsResponse, error)) *MockCloudService_UpdateNamespaceTags_Call {
	_c.Call.Return(run)
	return _c
}
