// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/cloud-sdk/api/cloudservice/v1"
	"google.golang.org/grpc"
)

// NewMockCloudService creates a new instance of MockCloudService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCloudService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCloudService {
	mock := &MockCloudService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCloudService is an autogenerated mock type for the CloudService type
type MockCloudService struct {
	mock.Mock
}

type MockCloudService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCloudService) EXPECT() *MockCloudService_Expecter {
	return &MockCloudService_Expecter{mock: &_m.Mock}
}

// GetNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespace(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *cloudservice.GetNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) *cloudservice.GetNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockCloudService_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespace_Call {
	return &MockCloudService_GetNamespace_Call{Call: _e.mock.On("GetNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) Return(getNamespaceResponse *cloudservice.GetNamespaceResponse, err error) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(getNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespaceResponse, error)) *MockCloudService_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaces provides a mock function for the type MockCloudService
func (_mock *MockCloudService) GetNamespaces(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaces")
	}

	var r0 *cloudservice.GetNamespacesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) *cloudservice.GetNamespacesResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.GetNamespacesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.GetNamespacesRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_GetNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaces'
type MockCloudService_GetNamespaces_Call struct {
	*mock.Call
}

// GetNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.GetNamespacesRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) GetNamespaces(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_GetNamespaces_Call {
	return &MockCloudService_GetNamespaces_Call{Call: _e.mock.On("GetNamespaces",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_GetNamespaces_Call) Run(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.GetNamespacesRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.GetNamespacesRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) Return(getNamespacesResponse *cloudservice.GetNamespacesResponse, err error) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(getNamespacesResponse, err)
	return _c
}

func (_c *MockCloudService_GetNamespaces_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.GetNamespacesRequest, opts ...grpc.CallOption) (*cloudservice.GetNamespacesResponse, error)) *MockCloudService_GetNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// RenameCustomSearchAttribute provides a mock function for the type MockCloudService
func (_mock *MockCloudService) RenameCustomSearchAttribute(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RenameCustomSearchAttribute")
	}

	var r0 *cloudservice.RenameCustomSearchAttributeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) *cloudservice.RenameCustomSearchAttributeResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.RenameCustomSearchAttributeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.RenameCustomSearchAttributeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_RenameCustomSearchAttribute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameCustomSearchAttribute'
type MockCloudService_RenameCustomSearchAttribute_Call struct {
	*mock.Call
}

// RenameCustomSearchAttribute is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.RenameCustomSearchAttributeRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) RenameCustomSearchAttribute(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_RenameCustomSearchAttribute_Call {
	return &MockCloudService_RenameCustomSearchAttribute_Call{Call: _e.mock.On("RenameCustomSearchAttribute",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Run(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.RenameCustomSearchAttributeRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.RenameCustomSearchAttributeRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) Return(renameCustomSearchAttributeResponse *cloudservice.RenameCustomSearchAttributeResponse, err error) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(renameCustomSearchAttributeResponse, err)
	return _c
}

func (_c *MockCloudService_RenameCustomSearchAttribute_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.RenameCustomSearchAttributeRequest, opts ...grpc.CallOption) (*cloudservice.RenameCustomSearchAttributeResponse, error)) *MockCloudService_RenameCustomSearchAttribute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespace provides a mock function for the type MockCloudService
func (_mock *MockCloudService) UpdateNamespace(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespace")
	}

	var r0 *cloudservice.UpdateNamespaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) *cloudservice.UpdateNamespaceResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudservice.UpdateNamespaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *cloudservice.UpdateNamespaceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCloudService_UpdateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespace'
type MockCloudService_UpdateNamespace_Call struct {
	*mock.Call
}

// UpdateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - req *cloudservice.UpdateNamespaceRequest
//   - opts ...grpc.CallOption
func (_e *MockCloudService_Expecter) UpdateNamespace(ctx interface{}, req interface{}, opts ...interface{}) *MockCloudService_UpdateNamespace_Call {
	return &MockCloudService_UpdateNamespace_Call{Call: _e.mock.On("UpdateNamespace",
		append([]interface{}{ctx, req}, opts...)...)}
}

func (_c *MockCloudService_UpdateNamespace_Call) Run(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *cloudservice.UpdateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*cloudservice.UpdateNamespaceRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) Return(updateNamespaceResponse *cloudservice.UpdateNamespaceResponse, err error) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(updateNamespaceResponse, err)
	return _c
}

func (_c *MockCloudService_UpdateNamespace_Call) RunAndReturn(run func(ctx context.Context, req *cloudservice.UpdateNamespaceRequest, opts ...grpc.CallOption) (*cloudservice.UpdateNamespaceResponse, error)) *MockCloudService_UpdateNamespace_Call {
	_c.Call.Return(run)
	return _c
}
