// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/gogo/protobuf/proto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrompter creates a new instance of MockPrompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrompter {
	mock := &MockPrompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrompter is an autogenerated mock type for the Prompter type
type MockPrompter struct {
	mock.Mock
}

type MockPrompter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrompter) EXPECT() *MockPrompter_Expecter {
	return &MockPrompter_Expecter{mock: &_m.Mock}
}

// PromptApply provides a mock function for the type MockPrompter
func (_mock *MockPrompter) PromptApply(old proto.Message, new proto.Message, verbose bool) error {
	ret := _mock.Called(old, new, verbose)

	if len(ret) == 0 {
		panic("no return value specified for PromptApply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(proto.Message, proto.Message, bool) error); ok {
		r0 = returnFunc(old, new, verbose)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPrompter_PromptApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptApply'
type MockPrompter_PromptApply_Call struct {
	*mock.Call
}

// PromptApply is a helper method to define mock.On call
//   - old proto.Message
//   - new proto.Message
//   - verbose bool
func (_e *MockPrompter_Expecter) PromptApply(old interface{}, new interface{}, verbose interface{}) *MockPrompter_PromptApply_Call {
	return &MockPrompter_PromptApply_Call{Call: _e.mock.On("PromptApply", old, new, verbose)}
}

func (_c *MockPrompter_PromptApply_Call) Run(run func(old proto.Message, new proto.Message, verbose bool)) *MockPrompter_PromptApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proto.Message
		if args[0] != nil {
			arg0 = args[0].(proto.Message)
		}
		var arg1 proto.Message
		if args[1] != nil {
			arg1 = args[1].(proto.Message)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPrompter_PromptApply_Call) Return(err error) *MockPrompter_PromptApply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPrompter_PromptApply_Call) RunAndReturn(run func(old proto.Message, new proto.Message, verbose bool) error) *MockPrompter_PromptApply_Call {
	_c.Call.Return(run)
	return _c
}

// PromptYes provides a mock function for the type MockPrompter
func (_mock *MockPrompter) PromptYes(message string, autoConfirm bool) (bool, error) {
	ret := _mock.Called(message, autoConfirm)

	if len(ret) == 0 {
		panic("no return value specified for PromptYes")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (bool, error)); ok {
		return returnFunc(message, autoConfirm)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) bool); ok {
		r0 = returnFunc(message, autoConfirm)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(message, autoConfirm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrompter_PromptYes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromptYes'
type MockPrompter_PromptYes_Call struct {
	*mock.Call
}

// PromptYes is a helper method to define mock.On call
//   - message string
//   - autoConfirm bool
func (_e *MockPrompter_Expecter) PromptYes(message interface{}, autoConfirm interface{}) *MockPrompter_PromptYes_Call {
	return &MockPrompter_PromptYes_Call{Call: _e.mock.On("PromptYes", message, autoConfirm)}
}

func (_c *MockPrompter_PromptYes_Call) Run(run func(message string, autoConfirm bool)) *MockPrompter_PromptYes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPrompter_PromptYes_Call) Return(b bool, err error) *MockPrompter_PromptYes_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPrompter_PromptYes_Call) RunAndReturn(run func(message string, autoConfirm bool) (bool, error)) *MockPrompter_PromptYes_Call {
	_c.Call.Return(run)
	return _c
}
